//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalcoCorporateFramawork.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MalcoCorporateFramawork.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] facebook_logo_colored {
            get {
                object obj = ResourceManager.GetObject("facebook_logo_colored", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] instagram_logo_colored {
            get {
                object obj = ResourceManager.GetObject("instagram_logo_colored", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] Isotipo_verde {
            get {
                object obj = ResourceManager.GetObject("Isotipo_verde", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] LinkedIn_logo_colored {
            get {
                object obj = ResourceManager.GetObject("LinkedIn_logo_colored", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;Cambio de contraseña&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///    &lt;div id=&quot;Logo&quot;&gt;
        ///        &lt;img style=&quot;display: block; margin-left: auto; margin-right: auto;&quot;
        ///            src=&quot;Isotipo_verde.png&quot; alt=&quot;MalCo Corporate&quot; width=&quot;154&quot; /&gt;
        ///    &lt;/div&gt;
        ///
        ///
        ///    &lt;div id=&quot;MainContainer&quot;&gt;
        ///        &lt;table style=&quot;background-color: transparent;&quot; width=&quot;600&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; align=&quot;center&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;left&quot;&gt;
        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string PasswordNotification {
            get {
                return ResourceManager.GetString("PasswordNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;Recuperacion de contraseña&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///    &lt;div id=&quot;Logo&quot;&gt;
        ///        &lt;img style=&quot;display: block; margin-left: auto; margin-right: auto;&quot;
        ///            src=&quot;Isotipo_verde.png&quot; alt=&quot;MalCo Corporate&quot; width=&quot;154&quot; /&gt;
        ///    &lt;/div&gt;
        ///
        ///
        ///    &lt;div id=&quot;MainContainer&quot;&gt;
        ///        &lt;table style=&quot;background-color: transparent;&quot; width=&quot;600&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; align=&quot;center&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;le [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Recover {
            get {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;Bienvenido&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///    &lt;div id=&quot;Logo&quot;&gt;
        ///        &lt;img style=&quot;display: block; margin-left: auto; margin-right: auto;&quot; src=&quot;Isotipo_verde.png&quot; alt=&quot;MalCo Corporate&quot; width=&quot;154&quot; /&gt;
        ///    &lt;/div&gt;
        ///
        ///    &lt;div id=&quot;MainContainer&quot;&gt;
        ///        &lt;table style=&quot;background-color: transparent;&quot; width=&quot;600&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; align=&quot;center&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;left&quot;&gt;
        ///                        &lt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] youtube_logo_colored {
            get {
                object obj = ResourceManager.GetObject("youtube_logo_colored", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
